# Generated by Django 4.1.2 on 2022-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contable',
            old_name='champs',
            new_name='champ',
        ),
        migrations.RenameField(
            model_name='contable',
            old_name='etape2',
            new_name='etape',
        ),
        migrations.AlterField(
            model_name='contable',
            name='type',
            field=models.CharField(choices=[('charfield', 'Text'), ('date', 'Date'), ('integer', 'number')], max_length=100, null=True),
        ),
    ]
