# Generated by Django 4.1.2 on 2022-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_champs_contable_champ_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynGt',
        ),
        migrations.AlterField(
            model_name='contable',
            name='type',
            field=models.CharField(choices=[('VARCHAR', 'Text'), ('DATE', 'Date'), ('BIGINT', 'number')], max_length=100, null=True),
        ),
    ]
